---
- hosts: webserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: absent
      update_cache: yes
