---
- hosts: webserver
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  tasks:
  - name: Install Docker
    apt:
      name: apt-transport-https
      state: latest  
  
  - name: certificates
    apt:
      name: ca-certificates
      state: latest

  - name: curl
    apt:
      name: curl
      state: latest

  - name: gnupg-agent
    apt:
      name: gnupg-agent
      state: latest

  - name: software-properties-common
    apt:
      name: software-properties-common
      state: latest
      update_cache: yes

  - name: Ansible Galaxy
    ansible-galaxy:
      name: geerlingguy.docker
