---
- hosts: ec2-18-222-191-249.us-east-2.compute.amazonaws.com
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
