---
- hosts: 172.31.42.210
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
